Maintenance release: v1.0.6 (#13)
* Using pinned versions of immutable Actions
* Use explicit immutable actions in sample workflow
* Use pinned commit in sample workflow and README
* Checksum verification for SpotBugs download
* Spaced out for readability
* Fixed link to LICENSE
* Changed to NOTE markup
* Updated CHANGELOG

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,6 +11,10 @@ inputs:
     description: 'The version of SpotBugs to use'
     required: false
     default: '4.7.3'
+  spotbugs_checksum:
+    description: 'The SHA256 checksum of the SpotBugs tarball'
+    required: false
+    default: 'f02e2f1135b23f3edfddb75f64be0491353cfeb567b5a584115aa4fd373d4431'
   findsecbugs_version:
     description: 'The version of FindSecBugs to use'
     required: false
@@ -59,38 +63,50 @@ runs:
   using: "composite"
   steps:
     - name: Setup Java
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@4.7.0
       with:
         distribution: ${{ inputs.java_distribution }}
         java-version: ${{ inputs.java_version }}
+
     - name: Cache SpotBugs
       if: inputs.no_cache == 'false'
       id: cache-spotbugs
-      uses: actions/cache@v3
+      uses: actions/cache@4.2.3
       with:
         path: ${{ inputs.base_path }}/spotbugs+/spotbugs-${{ inputs.spotbugs_version }}
         key: ${{ runner.os }}-spotbugs-${{ inputs.spotbugs_version }}
+
     - name: Cache FindSecBugs
       if: inputs.no_cache == 'false'
       id: cache-findsecbugs
-      uses: actions/cache@v3
+      uses: actions/cache@4.2.3
       with:
         path: ${{ inputs.base_path }}/findsecbugs+/findsecbugs-plugin-${{ inputs.findsecbugs_version }}.jar
         key: ${{ runner.os }}-findsecbugs-${{ inputs.findsecbugs_version }}
+
     - name: Get SpotBugs
       if: inputs.no_cache == 'true' || steps.cache-spotbugs.outputs.cache-hit != 'true'
       env:
         INPUT_SPOTBUGS_VERSION: ${{ inputs.spotbugs_version }}
+        INPUT_SPOTBUGS_CHECKSUM: ${{ inputs.spotbugs_checksum }}
         SPOTBUGS_HOME: ${{ inputs.base_path }}/spotbugs+/
       run: |
         mkdir -p "${SPOTBUGS_HOME}"
         cd "${SPOTBUGS_HOME}"
         wget -q -O spotbugs-"${INPUT_SPOTBUGS_VERSION}".tgz "https://github.com/spotbugs/spotbugs/releases/download/${INPUT_SPOTBUGS_VERSION}/spotbugs-${INPUT_SPOTBUGS_VERSION}.tgz"
+        if [ "${INPUT_SPOTBUGS_CHECKSUM}" != "" ]; then
+          echo "Checking checksum"
+          echo "${INPUT_SPOTBUGS_CHECKSUM}  spotbugs-${INPUT_SPOTBUGS_VERSION}.tgz" | sha256sum -c - || { echo "Checksum verification failed for spotbugs-${INPUT_SPOTBUGS_VERSION}.tgz"; exit 1; }
+        else
+          echo "No checksum provided, showing current checksum"
+          sha256sum spotbugs-"${INPUT_SPOTBUGS_VERSION}".tgz
+        fi
         tar -xzf spotbugs-"${INPUT_SPOTBUGS_VERSION}".tgz
         chmod +x spotbugs-"${INPUT_SPOTBUGS_VERSION}"/bin/spotbugs
         ls "spotbugs-${INPUT_SPOTBUGS_VERSION}.tgz"
         echo "Got spotbugs"
       shell: bash
+
     - name: Get FindSecBugs
       if: inputs.no_cache == 'true' || steps.cache-findsecbugs.outputs.cache-hit != 'true'
       env:
@@ -100,9 +116,12 @@ runs:
         mkdir -p "${FINDSECBUGS_HOME}"
         cd "${FINDSECBUGS_HOME}"
         wget -q -O "findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar" "https://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/${INPUT_FINDSECBUGS_VERSION}/findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar"
+        # Maven Central provides immutable versions, so we don't check the checksum, but do print it for traceability
+        sha256sum "findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar"
         ls "findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar"
         echo "Got findsecbugs"
       shell: bash
+
     - name: Run SpotBugs
       env:
         INPUT_FINDSECBUGS_VERSION: ${{ inputs.findsecbugs_version }}
@@ -118,6 +137,7 @@ runs:
         SPOTBUGS_FILES=$(find "${GITHUB_WORKSPACE}/${INPUT_SPOTBUGS_TARGET}" -type f -name "${INPUT_SPOTBUGS_GLOB}" -exec echo -n {} \+)
         "${SPOTBUGS_HOME}/bin/spotbugs" -maxHeap "${INPUT_RAM}" -textui -quiet -effort:max -low -bugCategories SECURITY -pluginList "${FINDSECBUGS_HOME}/findsecbugs-plugin-${INPUT_FINDSECBUGS_VERSION}.jar" -sarif=spotbugs.sarif ${SPOTBUGS_FILES}
       shell: bash
+
     - name: Adjust file paths
       if: inputs.path_prefix != ''
       env:
@@ -129,8 +149,9 @@ runs:
         mv spotbugs.sarif spotbugs_orig.sarif
         mv spotbugs_edited.sarif spotbugs.sarif
       shell: bash
+
     - name: Upload SARIF file
       if: inputs.upload_sarif == 'true'
-      uses: github/codeql-action/upload-sarif@v3
+      uses: github/codeql-action/upload-sarif@3.28.15
       with:
         sarif_file: ${{ inputs.base_path }}/spotbugs_working+/spotbugs.sarif
